# Generated by Django 2.2.5 on 2019-09-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_auto_20190925_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='positionx',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='positiony',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='positionx',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='positiony',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
