# Generated by Django 2.2.5 on 2019-09-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_auto_20190925_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='positionx',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='positiony',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
