# Generated by Django 2.2.5 on 2019-09-26 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_auto_20190925_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='positionx',
        ),
        migrations.RemoveField(
            model_name='player',
            name='positiony',
        ),
        migrations.RemoveField(
            model_name='room',
            name='positionx',
        ),
        migrations.RemoveField(
            model_name='room',
            name='positiony',
        ),
    ]
